version: '2'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test

  mysql2:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=foobar
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=wordpass
      #- MYSQL_USER=foobar

  psql:
    image: postgres:alpine
    container_name: psql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - POSTGRES_USER=root

  backup_mysql:
    image: jtilander/backup-db:latest
    environment:
      - DBTYPE=mysql
      - CONTAINER=mysql
      - USERNAME=root
      - PASSWORD=password
      - DBNAME=test
      - "CRONSCHEDULE=*/1 * * * *"
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/backup:/data
    command: cron

  backup_psql:
    image: jtilander/backup-db:latest
    environment:
      - DBTYPE=psql
      - CONTAINER=psql
      - USERNAME=root
      - PASSWORD=password
      - "CRONSCHEDULE=*/1 * * * *"
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/backup:/data
    command: cron

  backup_all:
    image: jtilander/backup-db:latest
    environment:
      - DBTYPE=all
      - "CRONSCHEDULE=*/1 * * * *"
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/backup:/data
    command: cron
